platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'ZPRingtone' do
  # use_frameworks!

pod 'AudioKit', '4.0.4'
pod 'Masonry', '1.1.0'
pod 'MBProgressHUD', '1.0.0'
pod 'MJExtension'
pod 'Aspects', '1.4.1'
pod 'TPKeyboardAvoiding', '1.3.1'
pod 'CTMediator', '12'
pod 'MJRefresh', '3.1.15.1'
pod 'YTKNetwork', '2.0.4'
end
